version: 2.1

jobs:
  build:
    docker:
      - image: node:alpine
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install

  docker_build:
    docker:
      - image: docker:19.03.12
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t node-app:latest .
            docker tag node-app:latest clementd01/nodejs-app:latest
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push clementd01/nodejs-app:latest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - docker_build:
          requires:
            - build
