version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14.17.0

    steps:
      - checkout

      - run:
          name: Build Docker image
          command: |
            docker build -t node_app .
